<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1530875558235" stop="1530875558292">
  <name>Scripts.test_001</name>
  <labels/>
  <test-cases>
    <test-case start="1530875558235" status="failed" stop="1530875558292">
      <name>Test_allure.test_01</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;Scripts.test_001.Test_allure object at 0x05F14C50&gt;

    def test_01(self):
&gt;       assert 0
E       assert 0

Scripts\test_001.py:10: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="37644-MainThread"/>
        <label name="host" value="DESKTOP-BOAILTF"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1530875558292" status="passed" stop="1530875558292">
      <name>Test_allure.test_02</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="37644-MainThread"/>
        <label name="host" value="DESKTOP-BOAILTF"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
